# SPDX-FileCopyrightText: 2021 The Manyverse Authors
#
# SPDX-License-Identifier: Unlicense

# You can add one username per supported platform and one custom link
patreon: andrestaltz
open_collective: manyverse
custom: https://manyver.se/donate
